/**
 * OpenAPI 3.1 spec for the public API. Served as JSON so integrators can
 * point Postman / Insomnia / openapi-typescript at it directly. The spec
 * is static (string template) — small enough to keep in source rather
 * than autogenerated.
 *
 * Adding a new endpoint requires updating this file. The
 * api-coverage test (below in this PR) walks `paths` and confirms each
 * declared route has a matching `route.ts` under `src/app/api/v1/`.
 */
import { NextResponse } from "next/server";

export const runtime = "nodejs";
export const dynamic = "force-static";

const spec = {
  openapi: "3.1.0",
  info: {
    title: "Renewal Radar Public API",
    version: "0.1.0",
    description:
      "Programmatic access to your subscriptions. Authentication via bearer API keys (Settings → API keys).",
  },
  servers: [{ url: "https://app.renewalradar.com/api/v1" }],
  components: {
    securitySchemes: {
      bearerAuth: {
        type: "http",
        scheme: "bearer",
        bearerFormat: "rr_pk_...",
      },
    },
    schemas: {
      Subscription: {
        type: "object",
        required: ["id", "vendor", "product", "status"],
        properties: {
          id: { type: "string", format: "uuid" },
          vendor: { type: "string" },
          product: { type: "string" },
          plan: { type: "string", nullable: true },
          status: { type: "string", enum: ["draft", "active", "paused", "pending_cancellation", "cancelled", "expired"] },
          billingCycle: { type: "string", enum: ["monthly", "quarterly", "annual", "multi_year"] },
          termStartDate: { type: "string", format: "date" },
          termEndDate: { type: "string", format: "date" },
          autoRenew: { type: "boolean" },
          noticePeriodDays: { type: "integer" },
          totalSeats: { type: "integer" },
          unitPriceCents: { type: "integer" },
          totalCostPerPeriodCents: { type: "integer" },
        },
      },
      CreateSubscriptionRequest: {
        type: "object",
        required: [
          "vendor",
          "product",
          "billingCycle",
          "termStartDate",
          "termEndDate",
          "autoRenew",
          "noticePeriodDays",
          "totalSeats",
          "unitPriceCents",
        ],
        properties: {
          vendor: { type: "string" },
          product: { type: "string" },
          plan: { type: "string", nullable: true },
          billingCycle: { type: "string", enum: ["monthly", "quarterly", "annual", "multi_year"] },
          termStartDate: { type: "string", format: "date" },
          termEndDate: { type: "string", format: "date" },
          autoRenew: { type: "boolean" },
          noticePeriodDays: { type: "integer", minimum: 0, maximum: 365 },
          totalSeats: { type: "integer", minimum: 1 },
          unitPriceCents: { type: "integer", minimum: 0 },
          notes: { type: "string", nullable: true },
          ownerEmail: {
            type: "string",
            format: "email",
            description: "Optional; assigns ownership when the email matches an existing user.",
          },
        },
      },
      Error: {
        type: "object",
        properties: {
          error: { type: "string" },
          message: { type: "string" },
        },
      },
    },
  },
  security: [{ bearerAuth: [] }],
  paths: {
    "/me": {
      get: {
        operationId: "getMe",
        summary: "Return the account associated with the calling API key.",
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    account: {
                      type: "object",
                      properties: {
                        id: { type: "string", format: "uuid" },
                        name: { type: "string" },
                        planTier: { type: "string" },
                      },
                    },
                    apiKey: {
                      type: "object",
                      properties: {
                        id: { type: "string", format: "uuid" },
                        name: { type: "string" },
                        scopes: { type: "array", items: { type: "string" } },
                        keyPrefix: { type: "string" },
                      },
                    },
                  },
                },
              },
            },
          },
          "401": { description: "Missing or invalid API key" },
          "403": { description: "Key missing the subscriptions:read scope" },
        },
      },
    },
    "/subscriptions": {
      get: {
        operationId: "listSubscriptions",
        summary: "List active subscriptions for the authenticated account.",
        parameters: [
          {
            name: "limit",
            in: "query",
            required: false,
            schema: { type: "integer", minimum: 1, maximum: 200, default: 50 },
          },
        ],
        responses: {
          "200": {
            description: "OK",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    data: {
                      type: "array",
                      items: { $ref: "#/components/schemas/Subscription" },
                    },
                    pagination: {
                      type: "object",
                      properties: {
                        limit: { type: "integer" },
                        count: { type: "integer" },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
      post: {
        operationId: "createSubscription",
        summary: "Create a subscription + renewal event.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: { $ref: "#/components/schemas/CreateSubscriptionRequest" },
            },
          },
        },
        responses: {
          "201": {
            description: "Created",
            headers: {
              Location: {
                description: "URL of the created subscription.",
                schema: { type: "string" },
              },
            },
          },
          "422": {
            description: "Validation error",
            content: {
              "application/json": {
                schema: { $ref: "#/components/schemas/Error" },
              },
            },
          },
        },
      },
    },
  },
} as const;

export function GET() {
  return NextResponse.json(spec);
}
